# Generated by Django 4.2.1 on 2023-05-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_navitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavItem',
        ),
    ]
