# Generated by Django 4.2 on 2023-05-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_delete_navitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
