# Generated by Django 4.2 on 2023-05-22 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_project_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='counter',
        ),
    ]
